export const systems = {
	ENGRAFI: 'ENGRAFI',
	MFS: 'MFS',
	CBS: 'CBS',
	NMS: 'NMS',
	BIOSIMREG: 'BIOSIMREG',
	VERIFICATION: 'VERIFICATION',
};

export const status = {
	SUCCESS: 'true',
	FAILURE: 'false',
};

export const serviceTypes = {
	SERVICE_REGISTRATION: 1,
	SERVICE_LINKING: 2,
	SERVICE_LINKING_SECURITY: 3,
	SERVICE_VERIFY_LINKING: 4,
	SERVICE_BIOCAPTURE: 5,
	SERVICE_CHECK_STATUS: 6,
	UNDEFINED: 99,
};

export const requestTypes = {
	NONBIOMETRIC_REGISTRATION: 1,
	NONBIOMETRIC_REGISTRATION_MFS: 2,
	NONBIOMETRIC_LINKING: 3,
	NONBIOMETRIC_LINKING_SECURITY: 4,
	PASSPORT_REGISTRATION: 5,
	PASSPORT_REGISTRATION_MFS: 6,
	PASSPORT_LINKING: 7,
	PASSPORT_LINKING_SECURITY: 8,
	UNDEFINED: 99,
};

export const paymentMode = {
	PREPAID: 'PREPAID',
	POST: 'POSTPAID',
	HYBRID: 'HYBRID',
};

export const documentTypes = {
	NATIONAL_ID: 1,
	PASSPORT: 2,
};
